name: Root Docker Build and Push

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Configure Docker to use gcloud as a credential helper
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker eu.gcr.io

      # Step 4: Build and Tag Docker Image
      - name: Build Docker Image
        run: |
          docker build \
            --file ./docker/build_and_push_root.Dockerfile \
            --tag eu.gcr.io/${{ secrets.PROJECT_ID }}/langflow-backend:latest \
            .

      # Step 5: Push Docker Image to GCR
      - name: Push Docker Image to GCR
        run: |
          docker push eu.gcr.io/${{ secrets.PROJECT_ID }}/langflow-backend:latest
